### ISSUE TITLE
how to set displayErrorDetails to true?

### ISSUE THREAD

**Issue by cnkt** [leroy0211/Slim-Symfony-Dependency-Injection-Bridge#4]
Class uses hard-coded value for displayErrorDetails. How can i change that without changing class?

**Comment by leroy0211** [comment]
Hmm.. I tried some several things out, but the only thing which came up my mind is to use something like this: 

```
$container = new \Flexsounds\Component\SymfonyContainerSlimBridge\ContainerBuilder();

$container->get('settings')->offsetSet('displayErrorDetails', true); 

$app = new \Slim\App($container);
```

Or you can use something in your Slim application Middleware to change this. 

I will update the code to use symfony parameters instead of hardcoded settings. So you can extend the settings. Or do you have any suggestions?

**Comment by cnkt** [comment]
I think your method is good. My only suggestion can be about documenting it.

**Comment by leroy0211** [comment]
@cnkt I created an update so you can change the default Slim Framework Settings. [See the docs](https://github.com/leroy0211/Slim-Symfony-Dependency-Injection-Bridge#default-parameters) how to use them. 
You should still be able to use the way described before.
